name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Images
        run: |
          docker build -t cicd-project-reactapp-image .

      - name: Push Docker Images (if using DockerHub)
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag cicd-project-reactapp-image ${{ secrets.DOCKER_USERNAME }}/cicd-project-reactapp-image
          docker push  ${{ secrets.DOCKER_USERNAME }}/cicd-project-reactapp-image